Numpy

Assignment Questions

1. What is a Python library? Why ^o we use Python libraries?

Python libraries are collections of pre-written code modules, functions, and classes that help solve specific problems or perform tasks in Python programs. We use them to save time, extend Python's capabilities, adhere to best practices, benefit from community support, and integrate advanced features into our projects.

2. What is the ^ifference between Numpy array an^ List?

NumPy arrays contain elements of the same data type, which allows for efficient mathematical operations, while lists can hold elements of different data types.

NumPy arrays are more memory efficient than lists, especially when dealing with large datasets, because they store homogeneous data types in contiguous memory locations.

NumPy arrays offer better performance for mathematical operations and numerical computations compared to lists, which are more suited for general-purpose data storage and manipulation

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4] <br>
[5, 6, 7, 8],<br>
[9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
d = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
arr = np.array(d)

In [10]:
arr.shape

(3, 4)

In [11]:
arr.size

12

In [12]:
arr.ndim

2

4. Write python code to access the first row of the following array?

In [13]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?


In [14]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
odd = arr[1::2]

In [16]:
odd

array([[5, 6, 7, 8]])

7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [18]:
np.random.rand(3,3)

array([[0.97012959, 0.68492174, 0.56447069],
       [0.25198813, 0.02673748, 0.84542578],
       [0.37569274, 0.13683626, 0.01867605]])

8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand:

1. Generates random numbers from a uniform distribution over the range [0, 1).
2. The generated numbers are uniformly distributed, meaning each value has an equal chance of being selected.
3. Takes parameters specifying the dimensions of the output array (e.g., shape=(3, 3) for a 3x3 matrix).

np.random.randn

1. Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
2. The generated numbers follow a bell-shaped curve centered around 0 i.e. normal distribution, with the majority of values clustered near the mean (0) and decreasing in frequency as they move away from the mean.
3. Does not require parameters for the dimensions of the output array; instead, it directly accepts the size of the array as arguments (e.g., np.random.randn(3, 3) for a 3x3 matrix)

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
expand_arr = np.expand_dims(arr,axis=0)

In [8]:
expand_arr.ndim

3

10. How to transpose the following array in NumPy?

In [9]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consi^er the following matrix:

matrixA =[[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]] <br>
matrixB =[[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication


In [11]:
matrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])


In [12]:
matrixA*matrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

2. matrix multiplication

In [17]:
matrixA = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

trans_b = np.transpose(matrixB)
result_dot = np.dot(matrixA, trans_b)
result_dot

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

3. Add both the matics

In [18]:
matrixA+matrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

4. Subtact matrixB from matrixA

In [19]:
matrixA - matrixB

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

5. Divide Matrix B by A

In [21]:
np.divide(matrixA,matrixB)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In [23]:
# np.ndarray.byteswap()

13. What is the significance of the np.linalg.inv function?

1. Solving Systems of Linear Equations
2. Matrix Decomposition:
3. Numerical Stability: 
4. Applications in Statistics and Machine Learning

14. What does the np.reshape function do, and how is it used?

In [24]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [25]:
np.reshape(arr1,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic operations. When performing operations between arrays of different shapes, NumPy automatically broadcasts the arrays to have compatible shapes so that the operation can be carried out element-wise.

In [26]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Define a 1D array
arr2 = np.array([10, 20, 30])

# Perform broadcasting in element-wise addition
result = arr1 + arr2

In [27]:
result

array([[11, 22, 33],
       [14, 25, 36]])

SyntaxError: invalid syntax (2357691903.py, line 1)